  
version: '3'

services:

  phoenix:
    build:
      context: ./api
    environment:
      PGUSER: postgres
      PGPASSWORD: 1234
      PGDATABASE: database_name
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: